### PR TITLE
add detects for hover and pointer mediq queries

### LINKED ISSUE #664: Detect support for `pointer` and `hover` media queries
http://dev.w3.org/csswg/mediaqueries4/#pointer

So we should use something along the lines of 

```js
var pointerMQSupported = Modernizr.mq('pointer:coarse') || Modernizr.mq('pointer:fine') ||  Modernizr.mq('pointer:none');
if (pointerMQSupported){
  var touchSupported = Modernizr.mq('pointer:coarse');
} else {
  //our current model
}
```

This has been implemented in WebKit. Let's track it down and use this first-class detection technique.

### PR DESCRIPTION
**Pull request by patrickkettner**
fixes #664

### CODE REVIEW

**Comment by patrickkettner** [comment]
@ryanseddon thoughts?

**Comment by ryanseddon** [comment]
sorry missed this mention

**Comment by ryanseddon** [comment]
Build seems to be failing due to some linting errors from this pr

**Comment by patrickkettner** [comment]
oh sure, blame the guy who wrote the code

**Comment by patrickkettner** [comment]
😆

**Pull request merged**
