### PR TITLE
ES7 - rest destructuring

### PR DESCRIPTION
**Pull request by dabretin**
Check for ES7 rest destructuring (!= ES6 rest parameters)
Ex: `const { a, ...rest } = { a: 1, b: 2, c: 3 }`

PS: widely inspired of es6/arrow

### CODE REVIEW

**Comment by dabretin** [comment]
**!!! Warning !!!**
It's wrong... In fact it just test destructuring rest in object (but not in array)

=> two possibilities:
- check destructuring rest in object and array in a single check (es7/destructuring-rest)
- create two tests (es7/destructuring-rest-array and es7/destructuring-rest-object)

=> What is your preference ?

**Comment by rejas** [comment]
you could make two tests in one file like in feature-detects/elem/track.js

**Comment by dabretin** [comment]
Done :)

**Comment by rejas** [comment]
could you fix the conflict so I can merge it?

**Comment by dabretin** [comment]
Done :)

**Pull request merged**
