### PR TITLE
fix issue #2520 - set scriptGlobalName causing an exception

### PR DESCRIPTION
**Pull request by HadadTomer**

### CODE REVIEW

**Comment by rejas** [comment]
first thing when doing a PR: check if the tests still pass :-)

**Comment by HadadTomer** [comment]
oops 👍 
found the issue with the test. on it

**Comment by mreinstein** [comment]
I _think_ this look ok to me, but truthfully it's been a long time since I've been in this codebase.

**Comment by HadadTomer** [comment]
@rejas merge? :)

**Comment by rejas** [comment]
Well, lets see if somethign breaks :-)

**Pull request merged**
