### PR TITLE
Update flexgap.js

### PR DESCRIPTION
**Pull request by TusharNaugain**
Added a check for Safari bug:

var isSupported = flexHeight === 1 || flexHeight === 2;
Reason: Safari, at zoom levels of 50% and 150%, returns scrollHeight as 2 instead of 1 for flex containers. This line ensures the test works across different browsers, including buggy Safari versions.

Fixes https://github.com/Modernizr/Modernizr/issues/2747

### CODE REVIEW

**Comment by rejas** [comment]
This looks very wrong, are you sure this is what you want to commit?

**Comment by TusharNaugain** [comment]
> This looks very wrong, are you sure this is what you want to commit?

No brother. This version of the code ensures that the flexgap test works properly in Safari, even when zoomed, by checking both possible values for scrollHeight.

**Comment by rejas** [comment]
No, you first committed this code:

grafik

Can you explain why?

**Comment by TusharNaugain** [comment]
@rejas could you please mention the label of hactoberfest and GSSSoc

**Pull request merged**
