### PR TITLE
Update and make html5shiv Browserify compatible

### PR DESCRIPTION
**Pull request by niksy**
This will resolve issue raised in this [comment](https://github.com/Modernizr/Modernizr/issues/1431#issuecomment-135287867).

### CODE REVIEW

**Comment by modernizr-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: f187f987da721bc0c0c81b92d66ab59e16773cdf
Build details: https://travis-ci.org/modernizr-savage/Modernizr/builds/82055406

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by patrickkettner** [comment]
looks like there are a ton of whitespace changes.

could you fix and squish to a single commit?

thanks!

**Comment by niksy** [comment]
@patrickkettner done!

**Comment by patrickkettner** [comment]
thanks!

**Comment by modernizr-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: f41627de53dbaa202ffae7bc88bf5dbc5ff3a66f
Build details: https://travis-ci.org/modernizr-savage/Modernizr/builds/82111063

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request merged**
