### PR TITLE
Solve Travis build config validation

### PR DESCRIPTION
**Pull request by MarkelFe**
Just a simple commit that solves the warnings from the view config section in Travis [(example)](https://travis-ci.org/github/Modernizr/Modernizr/builds/680532850/config)
```
root: deprecated key sudo (The key `sudo` has no effect anymore.)
root: missing dist, using the default xenial
root: missing os, using the default linux 
```
It wasn't particularly difficult as I had to do it before on a little project that I have MarkelFe/metacritic-crawler@bf09696

### CODE REVIEW

**Comment by rejas** [comment]
lgtm!

**Comment by rejas** [comment]
speaking of that travis config, @patrickkettner is ALL that stuff in there still necessary (or working?)

**Comment by rejas** [comment]
especially the notifications, the env properties and check against 0.12 travis node?

**Comment by patrickkettner** [comment]
no

**Comment by rejas** [comment]
What where they for?

**Comment by patrickkettner** [comment]
using git blame, looks like saucelabs, [savage](https://github.com/twbs/savage) and automatic gh-pages publication

**Comment by rejas** [comment]
I removed the stuff since it isnt working atm. At least for saucelabs there is an issue to get it working again: https://github.com/Modernizr/Modernizr/issues/2446

**Comment by patrickkettner** [comment]
LGTM

**Pull request merged**
