### PR TITLE
Add codecov support

### LINKED ISSUE #2447: Re-add coverage / coveralls support
Testing coverage with coveralls got removed when switching to gulp for the dev-pipeline. Wasnt maintained anyway on our side, so no real loss here.
If anyone wants to re-add it, feel free to do that :-)

### PR DESCRIPTION
**Pull request by MarkelFe**
Closes #2447 (kinda, but yes)
Related issue #2553

This PR adds coverage using the [codecov.io](https://codecov.io/) platform. It automatically uploads the coverage from [nyc](https://istanbul.js.org/) to [Codecov](https://codecov.io/). Here is an example of the result (only the last commit has coverage info) [https://codecov.io/gh/MarkelFe/Modernizr/branch/Markel-copy](https://codecov.io/gh/MarkelFe/Modernizr/branch/Markel-copy)

/* FROM HERE SAME FOR BOTH PRs SO DON'T READ IT 2 TIMES */

Okay, why are there 2 PR one with codecov and one with coveralls? Because [coveralls docs are 💩](https://docs.coveralls.io/javascript) so after maybe 15 tries I decided to switch to codecov which it has a little bit better docs, but most importantly, it has more updated articles. Once I was able to produce a result in codecov adapting it to coveralls was super fast, so that is why there are 2 PRs. Choose whichever platform you prefer and close the other pull request. As a note it will probably conflict with #2550 

And I want to take the last line to acknowledge how coverage platforms are horrible to configure. 2 days to find the correct 5 lines of code...!

### CODE REVIEW

**Comment by MarkelFe** [comment]
Okay, I wasn't expecting this comment, they [can be disabled if you want to](https://docs.codecov.io/docs/pull-request-comments)

**Comment by patrickkettner** [comment]
I like the  comment! thanks for setting this up @MarkelFe

**Comment by rejas** [comment]
I like this too. Thx a lot, merging directly!

**Comment by MarkelFe** [comment]
@rejas @patrickkettner you may want to enter codecov's website to link accounts

**Pull request merged**
