### PR TITLE
PR: Create module_type (Still Editing)

### PR DESCRIPTION
**Pull request by frank-dspeed**
Add support for es6 module support detection

### CODE REVIEW

**Comment by rejas** [comment]
Please use the code style from other tests, see async.js 
Your code is missing the js docs as well as the define-import of stuff used

**Comment by rejas** [comment]
hi @frank-dspeed still editing?

**Comment by frank-dspeed** [comment]
hehehe ya forgoten to finish that i will reschedule that

**Comment by frank-dspeed** [comment]
@rejas what exactly is missing now there are docs in the js file its now in config-all anything else left?

**Comment by frank-dspeed** [comment]
Lets close this PR some one else should do this i am not a modernizr user anymore.

**Pull request closed without merging**
