### PR TITLE
simplification of the src-set/sizes tests

### PR DESCRIPTION
**Pull request by f0rmat1k**
It's simpler and reduces the number of dependencies

### CODE REVIEW

**Comment by modernizr-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 0cc68eb32e3838c17576799d73a174ddec48b535
Build details: https://travis-ci.org/modernizr-savage/Modernizr/builds/60755612

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by f0rmat1k** [comment]
what is this platform?
@
```
Tested http://localhost:9999/test/index.html
Platform: ,firefox,beta
Passed: false
Url https://saucelabs.com/jobs/6c58fc8d686e4b35ac3072579fa880b8
```

**Comment by ryanseddon** [comment]
Looks like it's a caniuse mismatch with firefox beta. The platform is linux.

screen shot 2015-05-01 at 09 26 09

I'm sold on this simplification either what benefit does it have over the current one?

**Comment by f0rmat1k** [comment]
@ryanseddon I thought `new image` is faster, but it isn't, they equal.

**Pull request closed without merging**
