### PR TITLE
options should be case sensitive

### LINKED ISSUE #1674: Bower custom build error 502
I'm getting the following error installing the custom build via bower:

```
bower modernizr#*           not-cached https://modernizr.com/download?cssanimations-csscalc-csscolumns-csstransforms-csstransforms3d-csstransitions-flexbox-flexboxlegacy-flexboxtweener-flexwrap-localstorage-matchmedia-preserve3d-sessionstorage-printshiv-setclasses-shiv.zip#*
bower modernizr#*              resolve https://modernizr.com/download?cssanimations-csscalc-csscolumns-csstransforms-csstransforms3d-csstransitions-flexbox-flexboxlegacy-flexboxtweener-flexwrap-localstorage-matchmedia-preserve3d-sessionstorage-printshiv-setclasses-shiv.zip#*
bower modernizr#*             download https://modernizr.com/download?cssanimations-csscalc-csscolumns-csstransforms-csstransforms3d-csstransitions-flexbox-flexboxlegacy-flexboxtweener-flexwrap-localstorage-matchmedia-preserve3d-sessionstorage-printshiv-setclasses-shiv.zip
bower modernizr#*                EHTTP Status code of 502
```

### PR DESCRIPTION
**Pull request by patrickkettner**
fixes #1674

cc @ryanseddon @slexaxton

### CODE REVIEW

**Comment by modernizr-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 794130e9bbc8a5fc196805618240f3eac2674196
Build details: https://travis-ci.org/modernizr-savage/Modernizr/builds/82036814

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by modernizr-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 794130e9bbc8a5fc196805618240f3eac2674196
Build details: https://travis-ci.org/modernizr-savage/Modernizr/builds/82036814

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by SlexAxton** [comment]
cool cool :ship:

**Comment by patrickkettner** [comment]
the more I think about this the more I hate it. querystrings should be able to be insensitive.

**Pull request closed without merging**
