### PR TITLE
make sure test flash embed is removed when its been wrapped

### PR DESCRIPTION
**Pull request by patrickkettner**
fixes #1580

### CODE REVIEW

**Comment by modernizr-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: b00aa008e20253413581d4ac34ca779c85c9d061
Build details: https://travis-ci.org/modernizr-savage/Modernizr/builds/59094834

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by mari-na-bzzz** [comment]
How long will it take to create new package (3.0.0-alpha.4) with this fix? We are trying to decide what to do - use url-dependency to commit or wait for new package version.

**Comment by patrickkettner** [comment]
I will release one in a few hours.

**Comment by mari-na-bzzz** [comment]
thanks a lot)

**Comment by patrickkettner** [comment]
@mari-na-bzzz - its been released. sorry for the delay :]

**Comment by mari-na-bzzz** [comment]
:+1:

**Pull request merged**
