### PR TITLE
Adds feature detect and polyfill for window.matchMedia()

### PR DESCRIPTION
**Pull request by AlbertoElias**
Addresses #1518

### CODE REVIEW

**Comment by patrickkettner** [comment]
thanks for the PR @AlbertoElias!

there is also `msMatchMedia`, could you throw a `prefixed` check around it to cover that?

```
!!Modernizr.prefixed('matchMedia', window);
```

**Comment by AlbertoElias** [comment]
@patrickkettner Thanks for the quick response. Do you mean something like my last commit? Couldn't find the docs for that but found it being used elsewhere.

**Comment by patrickkettner** [comment]
Yep! Thanks so much. Could you squish them down to a single commi and then we will get it in?

**Comment by AlbertoElias** [comment]
@patrickkettner Done :)

**Comment by patrickkettner** [comment]
thanks mang!

**Pull request merged**
