### PR TITLE
PR: Create dynamic_import.js (Still Editing)

### PR DESCRIPTION
**Pull request by frank-dspeed**
Add dynamic imports check

### CODE REVIEW

**Comment by rejas** [comment]
thx for the pr @frank-dspeed could you fix the test errors?

**Comment by rejas** [comment]
One more thing: could you add your tests (also https://github.com/Modernizr/Modernizr/pull/2379)  to lib/config-all.json?

**Comment by rejas** [comment]
hi  @frank-dspeed still editing? :-)

**Comment by frank-dspeed** [comment]
@rejas at present i have no idea what is wrong with that meta i am not a heavy modernizer user there was a time as i tought it would be a good idea to use it but we can stop that PR some one else should take over

**Pull request closed without merging**
