### PR TITLE
Docs cleanup in mq.js

### PR DESCRIPTION
**Pull request by NikV**
I think for better organization, it should be switched to a full doc block.

### CODE REVIEW

**Comment by patrickkettner** [comment]
@NikV thanks a bunch for the PR! I would love to merge it, however its failing the jshint test. Could you remove the trailing whitespace, squash to a single commit, and then force push the change?

thanks again!

**Comment by NikV** [comment]
Fixed!

**Comment by patrickkettner** [comment]
great! could you just squish it down to a single commit?

cheers!

**Comment by NikV** [comment]
Creating a new Improved PR.

**Pull request closed without merging**
