### PR TITLE
Fetch automation script via `npm`

### PR DESCRIPTION
**Pull request by alrra**
Cc: @patrickkettner

### CODE REVIEW

**Comment by ryanseddon** [comment]
Hmm not sure why appveyor is not finding your package

screen shot 2015-09-18 at 10 31 24

**Comment by patrickkettner** [comment]
Its a acoped package, probably old npm. Need a before_install in its config
to update the global npm

**Comment by alrra** [comment]
> Its a acoped package, probably old npm.

Yes, that's the reason. Amended my commit and fixed it. :)

**Comment by ryanseddon** [comment]
Nice

**Pull request merged**
