### PR TITLE
Fix config generation when minifying

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/Modernizr/Modernizr/issues/2656

### CODE REVIEW

**Comment by rejas** [comment]
Thx for the PR, very much appreciated. Will pick it into the v3 branch and release a new version "soonish" (aka tomorrow if nothing goes wrong)

**Comment by rejas** [comment]
By the way: Do you feel adventourous enough to write a test for this so the code coverage goes up again?

**Comment by rejas** [comment]
Ok, "soonish" came quicker than I thought :-) Hope v3.11.8 helps your project a little!

**Comment by t3chguy** [comment]
Hah thanks, I ended manually mutating the minified output, and given we only rebuild modernizr every six months or so it'll come in handy for when I would have inevitably forgotten to mutate the minified output in another six months

**Pull request merged**
