### PR TITLE
umd wrapper. solves #1204

### PR DESCRIPTION
**Pull request by jtangelder**
This adds support for commonjs/amdjs. See #1204 for more info.

### CODE REVIEW

**Comment by ryanseddon** [comment]
lgtm @patrickkettner anything else you were waiting on?

**Comment by patrickkettner** [comment]
I always prefer 1 commit, but otherwise :+1:

**Comment by ryanseddon** [comment]
@jtangelder can you squash to 1 commit and then we'll merge.

**Comment by stucox** [comment]
Could you add a unit test? Slightly scared the builder, or some other change, *could* break this.

Plus we should get hotter on demanding tests for system changes.

**Comment by stucox** [comment]
FYI I don't think we'll have time to document this thoroghly for v3, so either it'll be an undocumented feature until 3.1, or we should hold off on merging.

**Comment by patrickkettner** [comment]
I'm fine with holding off until 3.1

**Pull request closed without merging**
