### PR TITLE
improve grammar in readme

### PR DESCRIPTION
**Pull request by barrstar**
I updated a few sentences to read a little more smoothly. This was also done to practice how to submit a pull request. So, no hard feelings if you do not wish to accept this change.

### CODE REVIEW

**Comment by patrickkettner** [comment]
enjoy gridiron!

**Comment by ryanseddon** [comment]
gridiron? Superb Owl on your mind? Isn't it flatiron?

**Comment by patrickkettner** [comment]
hah! whoopsie

**Comment by barrstar** [comment]
LOL! So yes, it's Flatiron (flatironschool.com). But thanks! :)

**Pull request closed without merging**
