### PR TITLE
Add link to temporary new webpage

### PR DESCRIPTION
**Pull request by rejas**
I managed to deploy an updated version of the webpage to new.modernizr.com since @patrickkettner doesnt seem to have time (or doesnt get any email anymore) for updating the old one. Maybe this gets the train rolling again...

Any idea on how to go onward with the page would be highly appreciated...

Fixes https://github.com/Modernizr/modernizr-neue/issues/140 and https://github.com/Modernizr/modernizr-neue/issues/141

### CODE REVIEW

**Comment by rejas** [comment]
@paulirish two month since @patrickkettner has promised to fix it. I have given up hope. If I dont hear back till tomorrow I'll merge my PR with the new link...

**Comment by paulirish** [comment]
@rejas sounds good

**Comment by rejas** [comment]
Grrrr..... Uploading the updated modernizr-neue to the new.modernizr.com worked and most of the pages are working. Unfortunatly the most important page: https://new.modernizr.com/download throws a network error after the first visit.... 

Anyone got an idea here? @patrickkettner? @paulirish? could you test the page on your side please?

**Comment by rejas** [comment]
Ah, had to run the server part of the site too which removes trailing spaces.... Unfortunatly thats not possible on github io pages so I fell back to deploy it on my private space:
https://rejas.uber.space/
Not sure know how much traffic modernizr.com generates but I am willing to host it there. Just the question if its possible to forward from modernizr.com to that site?

**Comment by magentox** [comment]
Actually none of those 3 websites seems to work correctly:
https://modernizr.com/ is still using modernizr 3.6.0 (news are locked on 3.5.0)
https://new.modernizr.com/ is still using modernizr 3.6.0 (the code is weird)
https://rejas.uber.space/ is a blank page

**Comment by patrickkettner** [comment]
@rejas few hundred thousand a month. the build server costs ~$200 a month. I will have an update for you later tonight.

**Comment by rejas** [comment]
So with your es6 rewrite, would the v3 page code be able to build modernizr v4 too? Or would we have to do some work there too **IF** we want to add that

**Comment by patrickkettner** [comment]
it would build the latest version of modernizr, so v4

**Comment by rejas** [comment]
So, could we have a update of the webpage @patrickkettner with the 3.11 note and all the ones before in the meantime?

**Comment by rejas** [comment]
Closing due to inactivity...

**Pull request closed without merging**
