### PR TITLE
Cleanup property tags

### PR DESCRIPTION
**Pull request by rejas**
Some property tags were not in all lowercase, thx to @patrickkettner for spotting them.

### CODE REVIEW

**Comment by patrickkettner** [comment]
is there a reason to duplicate the work of the PR? do you imagine it not being merged for a while?

**Comment by rejas** [comment]
I just want to get a cleaned up v3.11 out the door, then push for v4.

**Comment by patrickkettner** [comment]
LGTM

**Comment by rejas** [comment]
Will prepare a v3.11 release tomorrow. You got anything you think needs including in it? 
But first: bed time!

**Comment by patrickkettner** [comment]
:shipit:

**Pull request merged**
