### PR TITLE
Simplified build process

### PR DESCRIPTION
**Pull request by mahnunchik**
Hi @patrickkettner 

Sorry for my previous issue https://github.com/Modernizr/Modernizr/issues/1474

As promised this is my PR with the improvements of the build process.

The current implementation has the following disadvantages:
* Gruntfile appears as a set of hacks
* build.js file appears as a set of hacks for hacks
* build.js changes working directory (unpredictable consequences...)
* build.js overwrites the default config
* there are various build scripts on the server and on the Modernizr site

I tried to solve all these problems

* The general logic of build is extracted into a `build.js` file
* The build process does not need any temporary files
* File `src/generate.js` is moved to `lib/generate-init.js`
* `generate-init.js` and `build.js` files work in both cases: as Node module and as AMD module
* Grunt utilises `build.js` script to assembly default build

I hope you find my contributions useful :blush:

### CODE REVIEW

**Comment by mahnunchik** [comment]
Hi @Modernizr team,
Could we discuss these changes?

**Comment by mahnunchik** [comment]
Hi @patrickkettner,
I would like to improve Modernizr. But I can not move forward as long as I do not understand the suitability of these changes to the existing architecture.

**Comment by mahnunchik** [comment]
Hi,

Great work! https://github.com/Modernizr/Modernizr/commit/b8290c6f0bb57a47127d614725c40cc25ca4968d

Are you implement everything that is included in these PR?
* https://github.com/Modernizr/Modernizr/pull/1475
* https://github.com/Modernizr/Modernizr/pull/1488
* https://github.com/Modernizr/Modernizr/pull/1489

**Comment by patrickkettner** [comment]
yesir

**Pull request closed without merging**
