### PR TITLE
ensure modernizr can run inside an iframe

### PR DESCRIPTION
**Pull request by patrickkettner**
fixes #887

### CODE REVIEW

**Comment by modernizr-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 5482ad058fc2177364a4562f81796ad21a008aa7
Build details: https://travis-ci.org/modernizr-savage/Modernizr/builds/59091243

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by patrickkettner** [comment]
so none of the code _from_ #887 exists any longer, and from my local testing of this change there is no longer any issue actually running the full build inside of an iframe. 

@mikkotikkanen can you confirm that all that was needed to ensure its not broken is loading and parsing the script inside of the context of the iframe?

cc @ryanseddon @stucox

**Comment by modernizr-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 2c98c24f2fe8558754688c3e3dca607e7d5c744f
Build details: https://travis-ci.org/modernizr-savage/Modernizr/builds/59092585

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by mikkotikkanen** [comment]
Not really working on that project anymore, so no idea (my pull request is over 2 years old :P ). The test seems OK, though it's missing the case of running the Modernizr inside a scope. 

Something along the lines of...

```javascript
(function() {
  <insert Modernizr here>
})();
```

...so that `this` doesn't point to window.

**Comment by patrickkettner** [comment]
[we are not using `this` anymore](https://github.com/Modernizr/Modernizr/blob/master/lib/build.js#L30), so we should be golden.

**Pull request merged**
