### PR TITLE
Add Bower File

### PR DESCRIPTION
**Pull request by carmona**
adding bower.json file helps everyone using modernize as a bower component (currently we have to manually edit the files in order to use it)

### CODE REVIEW

**Comment by patrickkettner** [comment]
Hey @carmona!

Thanks a lot for the pull request - but we actually don't want to do this. There is not a single modernizr file as there was previously. We offer a bower downloading service rather than publishing to the official repo.

All you need to do is grab the build URL found at the top of any generated modernizr file 

screenshot of a modernizr build, higlighting the build url

and add a `.tar.gz` to the end of it.

Now you can add that to your `bower.json`, run the requisite install, and you have a built version ready for processing and deployment. 

`bower install --save https://modernizr.com/download?-cssanimations-csscalc-csscolumns-csstransforms.tar`

cheers, and thanks again

**Comment by carmona** [comment]
Well, thanks for the response but this method is not actually working. Are you sure it should load a tarball?

captura de tela 2015-10-05 as 15 29 20

Both `curl` and `wget` also get the whole html file for the download page.

**Comment by patrickkettner** [comment]
Remove the / after "download"

**Comment by carmona** [comment]
Got it working now, thanks a lot! Actually got a smaller build with just the features needed.

**Comment by patrickkettner** [comment]
awesome - thats why we do it :]

**Pull request closed without merging**
