### PR TITLE
Using Logo Modernizr In Readme.md

### PR DESCRIPTION
**Pull request by raihan71**
Using Logo Modernizr In Readme.md that made looks nicer

<strong>Before</strong>
image

<strong>After</strong>
image

### CODE REVIEW

**Comment by raihan71** [comment]
@rejas my first pr wdyt? 🤝

**Comment by Markel** [comment]
I personally like it a lot, maybe even change the alt from _Modernizr logo_ to _Modernizr_ and remove the h1

**Comment by raihan71** [comment]
> I personally like it a lot, maybe even change the alt from _Modernizr logo_ to _Modernizr_ and remove the h1

hi for sure! thanks for feedback, fixing!

**Comment by raihan71** [comment]
done fixed! @Markel @rejas

**Comment by rejas** [comment]
Thx for the PR!

**Comment by raihan71** [comment]
> Thx for the PR!

big thanks back!

**Pull request merged**
