### PR TITLE
Add new CodeOfConduct

### PR DESCRIPTION
**Pull request by rejas**
As proposed in https://github.com/Modernizr/Modernizr/issues/2358#issuecomment-412643266 I ran the cli to generate a CodeOfConduct.

Alas, which email adress should be used for contacting the team? 

The only contact option on the homepage is one form hosted by @paulirish ... 

Would love to get some input from the other owners like @patrickkettner @doctyper @SlexAxton @ryanseddon @stucox

### CODE REVIEW

**Comment by rejas** [comment]
Fixes https://github.com/Modernizr/Modernizr/issues/2358

**Comment by rejas** [comment]
> is the conduct@ setup as a mailing list?

i have no idea, that email was already written in the old defunct CoC so I took it over into this one. Only @patrickkettner could answer that

**Comment by KuraFire** [comment]
conduct@modernizr.com goes to the Modernizr Devs' mailing list.

**Comment by rejas** [comment]
there is a dev mailing list??? is there any traffic on that these days?

**Comment by rejas** [comment]
Merging this now. Mabye I can get on that dev mailing list @KuraFire @patrickkettner @paulirish  ?

**Pull request merged**
