### PR TITLE
Proposal: remove touchevents from the project

### PR DESCRIPTION
**Pull request by roblarsen**
This PR removes the `touchevents` detect from the project.

While renaming the test did, in fact, make the test accurately describe what it was testing, it still doesn't do what people think it does. this creates endless confusion (more than we see) and bug reports (the tip of the iceberg of people having problems with this detect.)

We can't create a test that does what people think this test does so we should end the confusion and remove the test. If people want the test in their projects it's an easy one to implement.

Additionally, I would argue that testing for what people _think_ this test does is harmful to users and contributing to that pattern (even via a misunderstanding of what this test does) is bad for the web.

See:

#2431
#2430
#2428
#2134
#548
#1731
#2156
#1628
#1225
#869
#1344
#1179
#884
#1161

### CODE REVIEW

**Comment by rejas** [comment]
+1 for this. I'd like to see some form of documentation about this removal in the docs through this PR too.

Additionally: Are there other tests like this that are confusing (because they test the brwoser, not the device) ?

**Comment by roblarsen** [comment]
IIRC all the docs are generated by the feature detects themselves, right? That would be weird here.

**Comment by rejas** [comment]
I thought of the normal README in the github as well as in https://modernizr.com/docs (that page is generated via hbs templates in modernizr-neue too)

**Comment by roblarsen** [comment]
I've got a branch with a docs update for this. I'll open a PR shortly.

**Comment by scott-thrillist** [comment]
https://github.com/Modernizr/Modernizr/commit/ab5febb484f2c8ebfed114459731ba65be20dfa2

Yes, please just remove it at this point. It really stinks that we can't reliably define how the user is interacting with their device so can do things such as preventing clicks from registering as a `hover` event on an iPad, but the more I think about it that's on the browser creators to sort out.

**Comment by roblarsen** [comment]
Sorry, I spaced on the other half of this!

**Comment by rejas** [comment]
NO worries @roblarsen but will you come back to it?

**Comment by roblarsen** [comment]
Sure, yeah. I have a branch with some docs, I don't remember where I was with that, but I'll pull it down and take a look

**Comment by rejas** [comment]
Just a thought: Maybe renaming it to "browsertouch" would be a good middleground (keeping it but indicating that its the brwoser not the device that is tested)?

**Comment by rejas** [comment]
Now officially deprecated with #2472

**Pull request closed without merging**
