### PR TITLE
Add known bug to inline SVG test

### PR DESCRIPTION
**Pull request by eltonmesquita**
Fixes #1553.

### CODE REVIEW

**Comment by patrickkettner** [comment]
Wanna just add this to #1553, rather than a separate commit?

**Comment by eltonmesquita** [comment]
Ops... Sorry... Gonna do it.

**Comment by patrickkettner** [comment]
dont be silly - no reason to be sorry at all!

On Wed, Mar 18, 2015 at 2:50 PM, Elton Mesquita <notifications@github.com>
wrote:

> Ops... Sorry... Gonna do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/pull/1558#issuecomment-83118986>.
>



-- 
patrick

**Comment by patrickkettner** [comment]
closing since #1553 merged

**Pull request closed without merging**
