### PR TITLE
Add audio autoplay feature detect

### PR DESCRIPTION
**Pull request by JordyvanDortmont**
I've adapted the video autoplay feature detect to also work for audio as requested in an older pull request: https://github.com/Modernizr/Modernizr/pull/1374.

### CODE REVIEW

**Comment by hakatashi** [comment]
I've adopted this commit and tried to minimize hard-coded audio data (for my personal usage). Maybe you can take a look at this.
https://github.com/hakatashi/Modernizr/commit/a8608f0acddb9a867e2335c4d4fb2af4636df729

**Comment by hakatashi** [comment]
> Did you ask @mudcube for permission for using the mp3 data URI or is that unnecessary?

I didn't find a license, but I think any copyright won't go on. It's just 0.00001 seconds of silence.

> Would you like me to put your commit on top of this pull request?

I don't mind.

**Comment by mudcube** [comment]
Thanks for asking, feel free to include! :)

**Comment by rejas** [comment]
Hi @JordyvanDortmont is this PR in your opinion ready to be reviewed?

**Comment by rejas** [comment]
Looks good to me, but I would like to get @patrickkettner opinion on the test before merging.

**Comment by patrickkettner** [comment]
sgood

**Pull request merged**
