### PR TITLE
ES6 rest parameters test

### PR DESCRIPTION
**Pull request by dabretin**
Check for rest parameters (implement in ES6)
`function check(...rest) {}`

### CODE REVIEW

**Comment by rejas** [comment]
this would fix #2511, right?

**Comment by dabretin** [comment]
You're right => closed

**Comment by dabretin** [comment]
Just a question:
For consistency, check for spread operator must exists (it's the opposite fo rest parameter).
I think it have to be a separate one but what's your preference ?

**Comment by rejas** [comment]
Yeah, seperate feature-detect would be my preference too

**Comment by rejas** [comment]
so, last one left, right? :-)

**Comment by dabretin** [comment]
Yes :)
But I dunno how to commit requested changes...

**Comment by rejas** [comment]
Thx a lot for your work!

**Comment by dabretin** [comment]
Ur welcome.
It's a honor to contribute to this great project :+1:

**Pull request merged**
